### ISSUE TITLE
Installing plugin

### ISSUE THREAD

**Issue by mooij88** [icecube45/Dash_InfinitiG37#1]
Hey mate,

I've successfully installed Dash and want to add your plug in to continue my G37 project (following your work and iCrap).
I can't seem to work out how to install your plugin? I've read your readme as the dash guide as well but cant wrap my head around it.

Any help would be greatly appreciated.

Thanks,

Adam

**Comment by xdsquared** [comment]
> Glad you got it figured out, let me know if you hit any difficulties

Hey, I have also got dsh and your plugin downloaded, but I don't see how to get dsh to recognize the plugin. I ran install script again for dash, but I still don't see an option for selecting your plugin. Is there another way to reinstall that I am missing? I also couldn't find where it says to reinstall dsh, I saw other buddies post and gave it a shot. Is there a link for that instruction? The directory I put the plugin in is dash/plugin/vehicle/. Any help would be awesome
